const ADD_WORKSPACE = "ADD_WORKSPACE";
const ADD_MULTIPLE_WORKSPACES = "ADD_MULTIPLE_WORKSPACES";
const DELETE_WORKSPACE = "DELETE_WORKSPACE";
const SET_CURRENT_WORKSPACE = "SET_CURRENT_WORKSPACE";

const types = {
    ADD_WORKSPACE,
    ADD_MULTIPLE_WORKSPACES,
    DELETE_WORKSPACE,
    SET_CURRENT_WORKSPACE
};

export default types;
